services:
  conjur-env-builder:
    build: 
      context: .
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
      - BUILDPACK_VERSION=${BUILDPACK_VERSION:-dev}
    volumes:
      - .:/conjur-env
      - ../vendor:/pkg
    command: >-
      sh -c 'go build -o /pkg/conjur-env -a
      -ldflags "-extldflags \"-static\" -X main.Version=${BUILDPACK_VERSION:-dev}"
      .'
  conjur-win-env-builder:
    build:
      context: .
    environment:
      - GOOS=windows
      - GOARCH=amd64
      - CGO_ENABLED=0
      - BUILDPACK_VERSION=${BUILDPACK_VERSION:-dev}
    volumes:
      - .:/conjur-env
      - ../vendor:/pkg
    command: >-
      sh -c 'go build -o /pkg/conjur-win-env.exe -a
      -ldflags "-extldflags \"-static\" -X main.Version=${BUILDPACK_VERSION:-dev}"
      .'