version: '2'
services:
  tester:
    build: .
    image: buildpack-tester

  postgres:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.1.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres
